# Permalinks
permalink:        pretty

# Settings
markdown:         kramdown
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             JBands
url:              http://jbands.michelthierry.org
description:      "Pretty sites from Japanese bands"
